export {default as Dash} from './dashboard.png'
export {default as Grad} from './graduated.png';
export {default as Chat} from './chat.png'
export {default as Settings} from './settings.png'
export {default as Teamwork} from './teamwork.png'
export {default as Manager} from './manager.png'
export {default as Teachers} from './teachers.png'
export {default as Curator} from './curator.png'
export {default as HW} from './HW.png'
export {default as Atten} from './attendance.png';
export {default as Level} from './level-up.png'
export {default as Course} from './course.png'